---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM-Moose
no_index:
  directory:
    - inc
    - t
requires:
  Moo: 0.009013
  Moose: 2.0604
  Moose::Autobox: 0.11
  MooseX::App::Cmd: 0
  MooseX::AttributeHelpers: 0.23
  MooseX::ClassAttribute: 0
  MooseX::Clone: 0
  MooseX::ConfigFromFile: 0
  MooseX::Declare: 0
  MooseX::Emulate::Class::Accessor::Fast: 0.00903
  MooseX::Getopt: 0.47
  MooseX::GlobRef: 0.0701
  MooseX::InsideOut: 0.106
  MooseX::Iterator: 0
  MooseX::LazyLogDispatch: 0
  MooseX::LazyRequire: 0.07
  MooseX::Log::Log4perl: 0
  MooseX::LogDispatch: 1.2002
  MooseX::MarkAsMethods: 0.14
  MooseX::Meta::TypeConstraint::ForceCoercion: 0.01
  MooseX::Method::Signatures: 0
  MooseX::MethodAttributes::Inheritable: 0.27
  MooseX::NonMoose: 0.22
  MooseX::Object::Pluggable: 0.0011
  MooseX::OneArgNew: 0.002
  MooseX::POE: 0
  MooseX::Param: 0
  MooseX::Params::Validate: 0.16
  MooseX::Role::Parameterized: 1.00
  MooseX::Role::TraitConstructor: 0.01
  MooseX::Role::WithOverloading: 0.09
  MooseX::SemiAffordanceAccessor: 0.09
  MooseX::SetOnce: 0.200001
  MooseX::SimpleConfig: 0
  MooseX::Singleton: 0.29
  MooseX::Storage: 0.30
  MooseX::StrictConstructor: 0.19
  MooseX::Traits: 0.11
  MooseX::Traits::Pluggable: 0.10
  MooseX::Types: 0.31
  MooseX::Types::Common::Numeric: 0.001007
  MooseX::Types::DateTime: 0.07
  MooseX::Types::LoadableClass: 0.007
  MooseX::Types::Path::Class: 0.05
  MooseX::Types::Perl: 0.101341
  MooseX::Types::Set::Object: 0.03
  MooseX::Types::Structured: 0.28
  Mouse: 0.97
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.06
